[package]
name = "alleycat-rs"
version = "0.1.0"
edition = "2024"
authors = ["Zach Koch <ezekeal@gmail.com>"]
license = "AGPL-3.0-only"

[workspace]
members = ["xtask"]
resolver = "3"

[lib]
path = "src/lib.rs"

[[bin]]
name = "alleycat-rs"
path = "src/main.rs"

[build-dependencies]
prost-build = "0.14.4"
protoc-bin-vendored = "3.2.0"

[dev-dependencies]
fake = "2.9"
claims = "0.7"
reqwest = { version = "0.13", features = ["json"] }
quickcheck= "1.0.3"
quickcheck_macros= "1"
rand = "0.8"
serde_json = "1"

[dependencies]
validator= "0.20"
unicode-segmentation= "1"
serde-aux = "4"
secrecy = { version= "0.8", features = ["serde"] }
config = "0.14"
actix-web = { version = "4", default-features = false }
tokio = { version= "1", features = ["macros", "rt-multi-thread"] }
serde = { version= "1", features = ["derive"]}
uuid = { version= "1", features = ["v4", "serde"] }
chrono = { version= "0.4.22", default-features = false, features = ["clock", "serde"] }
log= "0.4"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber= { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter= "0.3"
tracing-log = "0.2"
tracing-actix-web= "0.7"
prost = "0.14.4"

[dependencies.sqlx]
version= "0.8"
default-features = false
features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "mac_address",
    "migrate"
]
